// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoo_management.Database;

#nullable disable

namespace Zoo_management.Migrations
{
    [DbContext(typeof(ZooManagementContext))]
    partial class ZooManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("EnclosureZooKeeper", b =>
                {
                    b.Property<int>("EnclosuresEnclosureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZooKeepersZooKeeperId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnclosuresEnclosureId", "ZooKeepersZooKeeperId");

                    b.HasIndex("ZooKeepersZooKeeperId");

                    b.ToTable("EnclosureZooKeeper");
                });

            modelBuilder.Entity("Zoo_management.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateAcquired")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnclosureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZooKeeperId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnimalId");

                    b.HasIndex("EnclosureId");

                    b.HasIndex("ZooKeeperId");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 0",
                            Sex = "Male",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 2,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 1",
                            Sex = "Female",
                            Species = "Hippo",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 3,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 2",
                            Sex = "Male",
                            Species = "Elephant",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 4,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 3",
                            Sex = "Female",
                            Species = "Rhino",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 5,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 4",
                            Sex = "Male",
                            Species = "Giraffe",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 6,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 5",
                            Sex = "Female",
                            Species = "Ostritch",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 7,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 6",
                            Sex = "Male",
                            Species = "Zebra",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 8,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 7",
                            Sex = "Female",
                            Species = "Tiger",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 9,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 8",
                            Sex = "Male",
                            Species = "Hawk",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 10,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 9",
                            Sex = "Female",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 11,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 10",
                            Sex = "Male",
                            Species = "Hippo",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 12,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 11",
                            Sex = "Female",
                            Species = "Elephant",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 13,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 12",
                            Sex = "Male",
                            Species = "Rhino",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 14,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 13",
                            Sex = "Female",
                            Species = "Giraffe",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 15,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 14",
                            Sex = "Male",
                            Species = "Ostritch",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 16,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 15",
                            Sex = "Female",
                            Species = "Zebra",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 17,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 16",
                            Sex = "Male",
                            Species = "Tiger",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 18,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 17",
                            Sex = "Female",
                            Species = "Hawk",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 19,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 18",
                            Sex = "Male",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 20,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 19",
                            Sex = "Female",
                            Species = "Hippo",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 21,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 20",
                            Sex = "Male",
                            Species = "Elephant",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 22,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 21",
                            Sex = "Female",
                            Species = "Rhino",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 23,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 22",
                            Sex = "Male",
                            Species = "Giraffe",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 24,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 23",
                            Sex = "Female",
                            Species = "Ostritch",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 25,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 24",
                            Sex = "Male",
                            Species = "Zebra",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 26,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 25",
                            Sex = "Female",
                            Species = "Tiger",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 27,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 26",
                            Sex = "Male",
                            Species = "Hawk",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 28,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 27",
                            Sex = "Female",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 29,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 28",
                            Sex = "Male",
                            Species = "Hippo",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 30,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 29",
                            Sex = "Female",
                            Species = "Elephant",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 31,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 30",
                            Sex = "Male",
                            Species = "Rhino",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 32,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 31",
                            Sex = "Female",
                            Species = "Giraffe",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 33,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 32",
                            Sex = "Male",
                            Species = "Ostritch",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 34,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 33",
                            Sex = "Female",
                            Species = "Zebra",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 35,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 34",
                            Sex = "Male",
                            Species = "Tiger",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 36,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 35",
                            Sex = "Female",
                            Species = "Hawk",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 37,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 36",
                            Sex = "Male",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 38,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 37",
                            Sex = "Female",
                            Species = "Hippo",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 39,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 38",
                            Sex = "Male",
                            Species = "Elephant",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 40,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 39",
                            Sex = "Female",
                            Species = "Rhino",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 41,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 40",
                            Sex = "Male",
                            Species = "Giraffe",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 42,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 41",
                            Sex = "Female",
                            Species = "Ostritch",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 43,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 42",
                            Sex = "Male",
                            Species = "Zebra",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 44,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 43",
                            Sex = "Female",
                            Species = "Tiger",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 45,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 44",
                            Sex = "Male",
                            Species = "Hawk",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 46,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 45",
                            Sex = "Female",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 47,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 46",
                            Sex = "Male",
                            Species = "Hippo",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 48,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 47",
                            Sex = "Female",
                            Species = "Elephant",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 49,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 48",
                            Sex = "Male",
                            Species = "Rhino",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 50,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 49",
                            Sex = "Female",
                            Species = "Giraffe",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 51,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 50",
                            Sex = "Male",
                            Species = "Ostritch",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 52,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 51",
                            Sex = "Female",
                            Species = "Zebra",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 53,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 52",
                            Sex = "Male",
                            Species = "Tiger",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 54,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 53",
                            Sex = "Female",
                            Species = "Hawk",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 55,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 54",
                            Sex = "Male",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 56,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 55",
                            Sex = "Female",
                            Species = "Hippo",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 57,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 56",
                            Sex = "Male",
                            Species = "Elephant",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 58,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 57",
                            Sex = "Female",
                            Species = "Rhino",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 59,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 58",
                            Sex = "Male",
                            Species = "Giraffe",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 60,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 59",
                            Sex = "Female",
                            Species = "Ostritch",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 61,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 60",
                            Sex = "Male",
                            Species = "Zebra",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 62,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 61",
                            Sex = "Female",
                            Species = "Tiger",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 63,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 62",
                            Sex = "Male",
                            Species = "Hawk",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 64,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 63",
                            Sex = "Female",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 65,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 64",
                            Sex = "Male",
                            Species = "Hippo",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 66,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 65",
                            Sex = "Female",
                            Species = "Elephant",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 67,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 66",
                            Sex = "Male",
                            Species = "Rhino",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 68,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 67",
                            Sex = "Female",
                            Species = "Giraffe",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 69,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 68",
                            Sex = "Male",
                            Species = "Ostritch",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 70,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 69",
                            Sex = "Female",
                            Species = "Zebra",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 71,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 70",
                            Sex = "Male",
                            Species = "Tiger",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 72,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 71",
                            Sex = "Female",
                            Species = "Hawk",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 73,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 72",
                            Sex = "Male",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 74,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 73",
                            Sex = "Female",
                            Species = "Hippo",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 75,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 74",
                            Sex = "Male",
                            Species = "Elephant",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 76,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 75",
                            Sex = "Female",
                            Species = "Rhino",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 77,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 76",
                            Sex = "Male",
                            Species = "Giraffe",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 78,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 77",
                            Sex = "Female",
                            Species = "Ostritch",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 79,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 78",
                            Sex = "Male",
                            Species = "Zebra",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 80,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 79",
                            Sex = "Female",
                            Species = "Tiger",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 81,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 80",
                            Sex = "Male",
                            Species = "Hawk",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 82,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 81",
                            Sex = "Female",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 83,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 82",
                            Sex = "Male",
                            Species = "Hippo",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 84,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 83",
                            Sex = "Female",
                            Species = "Elephant",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 85,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 84",
                            Sex = "Male",
                            Species = "Rhino",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 86,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 85",
                            Sex = "Female",
                            Species = "Giraffe",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 87,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 86",
                            Sex = "Male",
                            Species = "Ostritch",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 88,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 87",
                            Sex = "Female",
                            Species = "Zebra",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 89,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 88",
                            Sex = "Male",
                            Species = "Tiger",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 90,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 89",
                            Sex = "Female",
                            Species = "Hawk",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 91,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 90",
                            Sex = "Male",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 92,
                            Classification = "Invertebrate",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 91",
                            Sex = "Female",
                            Species = "Hippo",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 93,
                            Classification = "Mammal",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 92",
                            Sex = "Male",
                            Species = "Elephant",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 94,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 93",
                            Sex = "Female",
                            Species = "Rhino",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 95,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 94",
                            Sex = "Male",
                            Species = "Giraffe",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 96,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 95",
                            Sex = "Female",
                            Species = "Ostritch",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 97,
                            Classification = "Fish",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 3,
                            Name = "Animalname 96",
                            Sex = "Male",
                            Species = "Zebra",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 98,
                            Classification = "Insect",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 4,
                            Name = "Animalname 97",
                            Sex = "Female",
                            Species = "Tiger",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 99,
                            Classification = "Bird",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 2,
                            Name = "Animalname 98",
                            Sex = "Male",
                            Species = "Hawk",
                            Status = "Active",
                            ZooKeeperId = 1
                        },
                        new
                        {
                            AnimalId = 100,
                            Classification = "Reptile",
                            DateAcquired = new DateOnly(2022, 7, 25),
                            DateOfBirth = new DateOnly(2018, 7, 15),
                            EnclosureId = 1,
                            Name = "Animalname 99",
                            Sex = "Female",
                            Species = "Lion",
                            Status = "Active",
                            ZooKeeperId = 1
                        });
                });

            modelBuilder.Entity("Zoo_management.Models.Enclosure", b =>
                {
                    b.Property<int>("EnclosureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxNumberOfAnimals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EnclosureId");

                    b.ToTable("Enclosure");

                    b.HasData(
                        new
                        {
                            EnclosureId = 1,
                            MaxNumberOfAnimals = 10,
                            Name = "Lion’s Enclosure"
                        },
                        new
                        {
                            EnclosureId = 2,
                            MaxNumberOfAnimals = 10,
                            Name = "Hippo’s Enclosure"
                        },
                        new
                        {
                            EnclosureId = 3,
                            MaxNumberOfAnimals = 50,
                            Name = "Aviary"
                        },
                        new
                        {
                            EnclosureId = 4,
                            MaxNumberOfAnimals = 40,
                            Name = "Reptile house"
                        },
                        new
                        {
                            EnclosureId = 5,
                            MaxNumberOfAnimals = 6,
                            Name = "Giraffe enclosure"
                        });
                });

            modelBuilder.Entity("Zoo_management.Models.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateOfTransfer")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferedZoo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Transfer");
                });

            modelBuilder.Entity("Zoo_management.Models.ZooKeeper", b =>
                {
                    b.Property<int>("ZooKeeperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ZooKeeperId");

                    b.ToTable("ZooKeeper");

                    b.HasData(
                        new
                        {
                            ZooKeeperId = 1,
                            Name = "Vani"
                        },
                        new
                        {
                            ZooKeeperId = 2,
                            Name = "Siuzanna"
                        });
                });

            modelBuilder.Entity("EnclosureZooKeeper", b =>
                {
                    b.HasOne("Zoo_management.Models.Enclosure", null)
                        .WithMany()
                        .HasForeignKey("EnclosuresEnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo_management.Models.ZooKeeper", null)
                        .WithMany()
                        .HasForeignKey("ZooKeepersZooKeeperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoo_management.Models.Animal", b =>
                {
                    b.HasOne("Zoo_management.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoo_management.Models.ZooKeeper", "ZooKeeper")
                        .WithMany("Animals")
                        .HasForeignKey("ZooKeeperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enclosure");

                    b.Navigation("ZooKeeper");
                });

            modelBuilder.Entity("Zoo_management.Models.Transfer", b =>
                {
                    b.HasOne("Zoo_management.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Zoo_management.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Zoo_management.Models.ZooKeeper", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
